version: '3.8'

networks:
  desafio-pgadmin:
    driver: bridge

volumes:
  desafio-pgadmin:

services:
  postgresql:
    image: postgres:latest
    volumes:
      - desafio-pgadmin:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespass
      PGDATA: /var/lib/postgresql/data
    networks:
      - desafio-pgadmin
    container_name: postgresql

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8080:80
      - 443:443
    depends_on: 
    - postgresql
    environment:
      - PGADMIN_DEFAULT_EMAIL=a@a.com
      - PGADMIN_DEFAULT_PASSWORD=pgadminpass
      # - PGADMIN_DEFAULT_PASSWORD_FILE=a@a.com
    networks:
      - desafio-pgadmin
    container_name: pgadmin4
